<table border="4">
	<tr>

		<th>ID</th>
		<th>Email</th>
		<th>Username</th>
		<th>Password</th>
		<th>Status</th>
		<th>Acción</th>

	</tr>
	<?php foreach ($this->usuarios as $usuario): ?>
	<tr>
		<td><?php echo $usuario['id']; ?></td>
		<td><?php echo $usuario['email']; ?></td>
		<td><?php echo $usuario['username']; ?></td>
		<td><?php echo $usuario['password']; ?></td>
		<td><?php echo $usuario['status']; ?></td>
		<td>
			<a href="<?php echo APP_URL."usuarios/edit/".$usuarios['id']; ?>">Editar</a>|
			<a href="<?php echo APP_URL."usuarios/delete/".$usuarios['id']; ?>">Eliminar</a>
		</td>

	</tr>
	<?php endforeach; ?>
</table>